[anykernel-kernelsu]
src.git = "https://github.com/Kernel-SU/AnyKernel3.git"
fetch.github = "Kernel-SU/AnyKernel3"

[anykernel-osm0sis]
src.git = "https://github.com/osm0sis/AnyKernel3.git"
fetch.github = "osm0sis/AnyKernel3"

[gcc-aarch64-linux-android]
src.git = "https://github.com/kindle4jerry/aarch64-linux-android-4.9-bakup.git"
fetch.github = "kindle4jerry/aarch64-linux-android-4.9-bakup"

[gcc-arm-linux-androideabi]
src.git = "https://github.com/KudProject/arm-linux-androideabi-4.9.git"
fetch.github = "KudProject/arm-linux-androideabi-4.9"

[kernelsu-stable]
# src.github = "tiann/KernelSU"
src.manual = "v0.9.5"
fetch.git = "https://github.com/tiann/KernelSU.git"

[kernelsu-stable-revision-code]
# src.webpage = "https://api.github.com/repos/tiann/KernelSU/releases?per_page=1"
# src.regex = "download\\/v[0-9\\._]+\\/KernelSU[^\"]*_([0-9]+)-release\\.apk"
src.manual = "11872"
fetch.url = "https://example.com"

[kernelsu-next]
src.github = "rifsxd/KernelSU-Next"
fetch.git = "https://github.com/rifsxd/KernelSU-Next.git"

[kernelsu-next-revision-code]
src.webpage = "https://api.github.com/repos/rifsxd/KernelSU-Next/releases?per_page=1"
src.regex = "download\\/v[0-9\\._]+\\/KernelSU[^\"]*_([0-9]+)-release\\.apk"
fetch.url = "https://example.com"

[linux-amazon-karnak]
src.git = "https://github.com/mt8163/android_kernel_amazon_karnak_4.9.git"
src.branch = "lineage-20.0"
fetch.github = "mt8163/android_kernel_amazon_karnak_4.9"

[linux-moto-rtwo-lineageos-21]
src.git = "https://github.com/LineageOS/android_kernel_motorola_sm8550.git"
src.branch = "lineage-21"
fetch.github = "LineageOS/android_kernel_motorola_sm8550"

[linux-moto-rtwo-lineageos-22_1]
src.git = "https://github.com/LineageOS/android_kernel_motorola_sm8550.git"
src.branch = "lineage-22.1"
fetch.github = "LineageOS/android_kernel_motorola_sm8550"

[linux-oneplus-8t-blu-spark]
src.git = "https://github.com/engstk/op8.git"
src.branch = "blu_spark-14-custom"
fetch.github = "engstk/op8"

[susfs-android13-5_15]
src.git = "https://gitlab.com/simonpunk/susfs4ksu.git"
src.branch = "gki-android13-5.15"
fetch.git = "https://gitlab.com/simonpunk/susfs4ksu.git"

[wildplus-kernel-patches]
src.git = "https://github.com/WildPlusKernel/kernel_patches.git"
fetch.github = "WildPlusKernel/kernel_patches"
